version: '3.9'
services:
  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - DJANGO_DEBUG=True
      - SECRET_KEY=your-secret-key
      - DATABASE_URL=sqlite:///db.sqlite3
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
  client:
    build: ./client
    command: npm run dev -- --host
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3003:3003"
    depends_on:
      - server
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: referral_db
      POSTGRES_USER: referral_user
      POSTGRES_PASSWORD: referral_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: 