# Generated by Django 4.2.7 on 2025-07-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
