# Generated by Django 4.2.7 on 2025-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give',
            name='location',
        ),
        migrations.AddField(
            model_name='give',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give',
            name='state',
            field=models.CharField(blank=True, choices=[('Gujarat', 'Gujarat - GJ'), ('Maharashtra', 'Maharashtra - MH'), ('Delhi', 'Delhi - DL'), ('Karnataka', 'Karnataka - KA'), ('Tamil Nadu', 'Tamil Nadu - TN'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='give',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
